include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: error
    unnecessary_null_comparison: error
    unrelated_type_equality_checks: error
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/ui/debug/spike_map_painter.dart
    - lib/ui/debug/spike_canvas_screen.dart
    - build/**

linter:
  rules:
    - always_declare_return_types
    - prefer_final_fields
    - prefer_final_locals
    - require_trailing_commas
    - unawaited_futures
